import {
  TextInput, ReferenceInput, AutocompleteInput, useRecordContext, useNotify,
} from 'react-admin';
import { QuickCreateContact } from './quickCreate';
import { bySortName } from './vocab';
import { useWatch, useFormState } from 'react-hook-form';
import { Box, Button, Typography } from '@mui/material';
import CopyIcon from '@mui/icons-material/ContentCopy';

const LIMIT = 255;

/*
 * The comment written into a pitched MP3, as DISCO carries it. Generated by
 * the database from the catalog (this recording's pitch contact, one stop,
 * stems and alternates, vocals, moods, tempo, genres, sounds like), so the
 * preview reflects the last save. Text typed below replaces it for this
 * recording.
 */
export const PitchCommentInput = () => {
  const record = useRecordContext();
  const override = useWatch({ name: 'pitch_comment' });
  const { isDirty } = useFormState();
  const notify = useNotify();

  const picked = useWatch({ name: 'pitch_contact_id' });
  const own = (override || '').trim();
  const missing = record?.id && !picked && !record?.has_pitch_contact;
  const pickerHelp = picked
    ? 'Their name, primary email, and phone start the comment'
    : record?.pitch_contact_used
      ? `Blank uses ${record.pitch_contact_used}`
      : 'Blank uses the default contact from Settings, Pitch settings';
  const text = own || record?.pitch_comment_auto || '';
  const count = text.length;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      notify('Pitch comment copied', { type: 'info' });
    } catch {
      notify('Could not copy; select the text and copy it instead', { type: 'warning' });
    }
  };

  return (
    <Box sx={{ mt: 3, width: '100%', maxWidth: 760 }}>
      <Typography variant="subtitle2">Pitch comment</Typography>
      <ReferenceInput source="pitch_contact_id" reference="contact" perPage={200}
                      sort={{ field: 'sort_name', order: 'ASC' }}>
        <AutocompleteInput optionText="sort_name" label="Pitch contact"
                           filterToQuery={bySortName}
                           create={<QuickCreateContact />}
                           createLabel="Type to search or add a person"
                           helperText={pickerHelp}
                           sx={{ width: { xs: '100%', md: 360 }, mt: 1 }} />
      </ReferenceInput>
      {missing && (
        <Typography variant="body2" sx={{ color: 'error.main', mt: 1 }}>
          No pitch contact: this recording would go out with nobody to call. Pick
          someone above, or set a default under Settings, Pitch settings.
        </Typography>
      )}
      <Typography variant="body2"
                  sx={{ whiteSpace: 'pre-wrap', p: 1.5, my: 1, border: 1,
                        borderColor: 'divider', borderRadius: 1, minHeight: 48 }}>
        {text || 'Nothing to say yet. Pick a pitch contact above, and add vocals, moods, or genres.'}
      </Typography>
      <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', mb: 1 }}>
        <Typography variant="body2" sx={{ color: count > LIMIT ? 'error.main' : 'text.secondary' }}>
          {count} / {LIMIT} {own ? '(your own text)' : '(generated'}
          {!own && (isDirty ? ', as of the last save)' : ')')}
        </Typography>
        <Button size="small" startIcon={<CopyIcon />} onClick={copy} disabled={!text}>
          Copy
        </Button>
      </Box>
      <TextInput source="pitch_comment" label="Write your own instead" multiline fullWidth
                 helperText="Leave blank to use the generated comment. Apple shows up to 255 characters." />
    </Box>
  );
};
